loki:
  enabled: true
  isDefault: false

  image:
    tag: 2.9.10

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

  limits_config:
    creation_grace_period: 24h
    reject_old_samples: true
    reject_old_samples_max_age: 168h

promtail:
  enabled: false
#  config:
#    lokiAddress: http://loki-stack:3100/loki/api/v1/push
