apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: landing-page-uptime
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  jobName: landing-page-check
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://joshdarcy.xyz
        - https://www.google.com
        - https://www.cloudflare.com
        - https://1.1.1.1
  interval: 15s
