---
config:
  clients:
    - url: http://loki-stack.monitoring.svc:3100/loki/api/v1/push

  snippets:
    extraScrapeConfigs: |
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:1514
          labels:
            job: syslog
        relabel_configs:
          - source_labels: [__syslog_message_hostname]
            target_label: host

service:
  enabled: true
  type: ClusterIP

extraObjects:
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: promtail-syslog
      namespace: monitoring
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: promtail
      ports:
        - name: syslog
          port: 514
          targetPort: 1514
          nodePort: 30514
          protocol: TCP
