---
hostNetwork: false

config:
  clients:
    - url: http://loki-stack.monitoring.svc:3100/loki/api/v1/push

  snippets:
    extraScrapeConfigs: |
      - job_name: syslog
        syslog:
          listen_address: ${POD_IP}:1514
          listen_protocol: udp
          labels:
            job: syslog
        relabel_configs:
          - source_labels: [__syslog_message_hostname]
            target_label: host
        pipeline_stages:
          - timestamp:
              source: force_failure
              format: RFC3339
              action_on_failure: fudge

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: promtail-syslog
      namespace: monitoring
      labels:
        app.kubernetes.io/name: promtail
    spec:
      type: NodePort
      externalTrafficPolicy: Local
      selector:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: promtail
      ports:
        - name: syslog
          port: 514
          targetPort: 1514
          nodePort: 30514
          protocol: UDP

extraPorts: []
extraEnv: []
