---
hostNetwork: true

config:
  clients:
    - url: http://loki-stack.monitoring.svc:3100/loki/api/v1/push

  snippets:
    extraScrapeConfigs: |
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:30514
          listen_protocol: udp
          labels:
            job: syslog
        relabel_configs:
          - source_labels: [__syslog_message_hostname]
            target_label: host
        pipeline_stages:
          - timestamp:
              source: force_failure
              format: RFC3339
              action_on_failure: fudge

extraPorts: []

service:
  enabled: false
extraObjects: []

extraEnv:
  - name: TZ
    value: "Australia/Brisbane"
